# Generated by Django 4.2.9 on 2026-04-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('api_request', 'API Request'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('model_trained', 'Model Trained'), ('admin_action', 'Admin Action'), ('system', 'System'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change')], default='system', max_length=50),
        ),
    ]
